version: '2.2'

services:
  small:
    build:
      context: ../
    container_name: small
    command: stress --vm-hang 60 -m 2
    mem_limit: 515m
    memswap_limit: 515m
    mem_swappiness: 0
  crash:
    build:
      context: ../
    container_name: crash
    command: stress --vm-hang 60 -m 3
    mem_limit: 515m
    memswap_limit: 515m
    mem_swappiness: 0
