version: '2.2'

services:
  stress1:
    build:
      context: ../
    command: stress -c 2
    container_name: cpu_shares_stress1
    cpu_shares: 512
  stress2:
    build:
      context: ../
    command: stress -c 2
    container_name: cpu_shares_stress2
    cpu_shares: 1024
